// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that AdminRunsAPIMock does implement AdminRunsAPI.
// If this is not the case, regenerate this file with moq.
var _ AdminRunsAPI = &AdminRunsAPIMock{}

// AdminRunsAPIMock is a mock implementation of AdminRunsAPI.
//
//	func TestSomethingThatUsesAdminRunsAPI(t *testing.T) {
//
//		// make and configure a mocked AdminRunsAPI
//		mockedAdminRunsAPI := &AdminRunsAPIMock{
//			ForceCancelFunc: func(ctx context.Context, runID string, options tfe.AdminRunForceCancelOptions) error {
//				panic("mock out the ForceCancel method")
//			},
//			ListFunc: func(ctx context.Context, options *tfe.AdminRunsListOptions) (*tfe.AdminRunsList, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedAdminRunsAPI in code that requires AdminRunsAPI
//		// and then make assertions.
//
//	}
type AdminRunsAPIMock struct {
	// ForceCancelFunc mocks the ForceCancel method.
	ForceCancelFunc func(ctx context.Context, runID string, options tfe.AdminRunForceCancelOptions) error

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, options *tfe.AdminRunsListOptions) (*tfe.AdminRunsList, error)

	// calls tracks calls to the methods.
	calls struct {
		// ForceCancel holds details about calls to the ForceCancel method.
		ForceCancel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RunID is the runID argument value.
			RunID string
			// Options is the options argument value.
			Options tfe.AdminRunForceCancelOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options *tfe.AdminRunsListOptions
		}
	}
	lockForceCancel sync.RWMutex
	lockList        sync.RWMutex
}

// ForceCancel calls ForceCancelFunc.
func (mock *AdminRunsAPIMock) ForceCancel(ctx context.Context, runID string, options tfe.AdminRunForceCancelOptions) error {
	if mock.ForceCancelFunc == nil {
		panic("AdminRunsAPIMock.ForceCancelFunc: method is nil but AdminRunsAPI.ForceCancel was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RunID   string
		Options tfe.AdminRunForceCancelOptions
	}{
		Ctx:     ctx,
		RunID:   runID,
		Options: options,
	}
	mock.lockForceCancel.Lock()
	mock.calls.ForceCancel = append(mock.calls.ForceCancel, callInfo)
	mock.lockForceCancel.Unlock()
	return mock.ForceCancelFunc(ctx, runID, options)
}

// ForceCancelCalls gets all the calls that were made to ForceCancel.
// Check the length with:
//
//	len(mockedAdminRunsAPI.ForceCancelCalls())
func (mock *AdminRunsAPIMock) ForceCancelCalls() []struct {
	Ctx     context.Context
	RunID   string
	Options tfe.AdminRunForceCancelOptions
} {
	var calls []struct {
		Ctx     context.Context
		RunID   string
		Options tfe.AdminRunForceCancelOptions
	}
	mock.lockForceCancel.RLock()
	calls = mock.calls.ForceCancel
	mock.lockForceCancel.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *AdminRunsAPIMock) List(ctx context.Context, options *tfe.AdminRunsListOptions) (*tfe.AdminRunsList, error) {
	if mock.ListFunc == nil {
		panic("AdminRunsAPIMock.ListFunc: method is nil but AdminRunsAPI.List was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Options *tfe.AdminRunsListOptions
	}{
		Ctx:     ctx,
		Options: options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedAdminRunsAPI.ListCalls())
func (mock *AdminRunsAPIMock) ListCalls() []struct {
	Ctx     context.Context
	Options *tfe.AdminRunsListOptions
} {
	var calls []struct {
		Ctx     context.Context
		Options *tfe.AdminRunsListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
