// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that AgentPoolsAPIMock does implement AgentPoolsAPI.
// If this is not the case, regenerate this file with moq.
var _ AgentPoolsAPI = &AgentPoolsAPIMock{}

// AgentPoolsAPIMock is a mock implementation of AgentPoolsAPI.
//
//	func TestSomethingThatUsesAgentPoolsAPI(t *testing.T) {
//
//		// make and configure a mocked AgentPoolsAPI
//		mockedAgentPoolsAPI := &AgentPoolsAPIMock{
//			ListFunc: func(ctx context.Context, organization string, options *tfe.AgentPoolListOptions) (*tfe.AgentPoolList, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedAgentPoolsAPI in code that requires AgentPoolsAPI
//		// and then make assertions.
//
//	}
type AgentPoolsAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, organization string, options *tfe.AgentPoolListOptions) (*tfe.AgentPoolList, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization string
			// Options is the options argument value.
			Options *tfe.AgentPoolListOptions
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *AgentPoolsAPIMock) List(ctx context.Context, organization string, options *tfe.AgentPoolListOptions) (*tfe.AgentPoolList, error) {
	if mock.ListFunc == nil {
		panic("AgentPoolsAPIMock.ListFunc: method is nil but AgentPoolsAPI.List was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.AgentPoolListOptions
	}{
		Ctx:          ctx,
		Organization: organization,
		Options:      options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, organization, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedAgentPoolsAPI.ListCalls())
func (mock *AgentPoolsAPIMock) ListCalls() []struct {
	Ctx          context.Context
	Organization string
	Options      *tfe.AgentPoolListOptions
} {
	var calls []struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.AgentPoolListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
