// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that PlansAPIMock does implement PlansAPI.
// If this is not the case, regenerate this file with moq.
var _ PlansAPI = &PlansAPIMock{}

// PlansAPIMock is a mock implementation of PlansAPI.
//
//	func TestSomethingThatUsesPlansAPI(t *testing.T) {
//
//		// make and configure a mocked PlansAPI
//		mockedPlansAPI := &PlansAPIMock{
//			ReadFunc: func(ctx context.Context, planID string) (*tfe.Plan, error) {
//				panic("mock out the Read method")
//			},
//			ReadJSONOutputFunc: func(ctx context.Context, planID string) ([]byte, error) {
//				panic("mock out the ReadJSONOutput method")
//			},
//		}
//
//		// use mockedPlansAPI in code that requires PlansAPI
//		// and then make assertions.
//
//	}
type PlansAPIMock struct {
	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, planID string) (*tfe.Plan, error)

	// ReadJSONOutputFunc mocks the ReadJSONOutput method.
	ReadJSONOutputFunc func(ctx context.Context, planID string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PlanID is the planID argument value.
			PlanID string
		}
		// ReadJSONOutput holds details about calls to the ReadJSONOutput method.
		ReadJSONOutput []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PlanID is the planID argument value.
			PlanID string
		}
	}
	lockRead           sync.RWMutex
	lockReadJSONOutput sync.RWMutex
}

// Read calls ReadFunc.
func (mock *PlansAPIMock) Read(ctx context.Context, planID string) (*tfe.Plan, error) {
	if mock.ReadFunc == nil {
		panic("PlansAPIMock.ReadFunc: method is nil but PlansAPI.Read was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		PlanID string
	}{
		Ctx:    ctx,
		PlanID: planID,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, planID)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedPlansAPI.ReadCalls())
func (mock *PlansAPIMock) ReadCalls() []struct {
	Ctx    context.Context
	PlanID string
} {
	var calls []struct {
		Ctx    context.Context
		PlanID string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// ReadJSONOutput calls ReadJSONOutputFunc.
func (mock *PlansAPIMock) ReadJSONOutput(ctx context.Context, planID string) ([]byte, error) {
	if mock.ReadJSONOutputFunc == nil {
		panic("PlansAPIMock.ReadJSONOutputFunc: method is nil but PlansAPI.ReadJSONOutput was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		PlanID string
	}{
		Ctx:    ctx,
		PlanID: planID,
	}
	mock.lockReadJSONOutput.Lock()
	mock.calls.ReadJSONOutput = append(mock.calls.ReadJSONOutput, callInfo)
	mock.lockReadJSONOutput.Unlock()
	return mock.ReadJSONOutputFunc(ctx, planID)
}

// ReadJSONOutputCalls gets all the calls that were made to ReadJSONOutput.
// Check the length with:
//
//	len(mockedPlansAPI.ReadJSONOutputCalls())
func (mock *PlansAPIMock) ReadJSONOutputCalls() []struct {
	Ctx    context.Context
	PlanID string
} {
	var calls []struct {
		Ctx    context.Context
		PlanID string
	}
	mock.lockReadJSONOutput.RLock()
	calls = mock.calls.ReadJSONOutput
	mock.lockReadJSONOutput.RUnlock()
	return calls
}
