// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that PoliciesAPIMock does implement PoliciesAPI.
// If this is not the case, regenerate this file with moq.
var _ PoliciesAPI = &PoliciesAPIMock{}

// PoliciesAPIMock is a mock implementation of PoliciesAPI.
//
//	func TestSomethingThatUsesPoliciesAPI(t *testing.T) {
//
//		// make and configure a mocked PoliciesAPI
//		mockedPoliciesAPI := &PoliciesAPIMock{
//			ListFunc: func(ctx context.Context, organization string, options *tfe.PolicyListOptions) (*tfe.PolicyList, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedPoliciesAPI in code that requires PoliciesAPI
//		// and then make assertions.
//
//	}
type PoliciesAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, organization string, options *tfe.PolicyListOptions) (*tfe.PolicyList, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization string
			// Options is the options argument value.
			Options *tfe.PolicyListOptions
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *PoliciesAPIMock) List(ctx context.Context, organization string, options *tfe.PolicyListOptions) (*tfe.PolicyList, error) {
	if mock.ListFunc == nil {
		panic("PoliciesAPIMock.ListFunc: method is nil but PoliciesAPI.List was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.PolicyListOptions
	}{
		Ctx:          ctx,
		Organization: organization,
		Options:      options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, organization, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedPoliciesAPI.ListCalls())
func (mock *PoliciesAPIMock) ListCalls() []struct {
	Ctx          context.Context
	Organization string
	Options      *tfe.PolicyListOptions
} {
	var calls []struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.PolicyListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
