// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that PolicySetsAPIMock does implement PolicySetsAPI.
// If this is not the case, regenerate this file with moq.
var _ PolicySetsAPI = &PolicySetsAPIMock{}

// PolicySetsAPIMock is a mock implementation of PolicySetsAPI.
//
//	func TestSomethingThatUsesPolicySetsAPI(t *testing.T) {
//
//		// make and configure a mocked PolicySetsAPI
//		mockedPolicySetsAPI := &PolicySetsAPIMock{
//			ListFunc: func(ctx context.Context, organization string, options *tfe.PolicySetListOptions) (*tfe.PolicySetList, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedPolicySetsAPI in code that requires PolicySetsAPI
//		// and then make assertions.
//
//	}
type PolicySetsAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, organization string, options *tfe.PolicySetListOptions) (*tfe.PolicySetList, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization string
			// Options is the options argument value.
			Options *tfe.PolicySetListOptions
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *PolicySetsAPIMock) List(ctx context.Context, organization string, options *tfe.PolicySetListOptions) (*tfe.PolicySetList, error) {
	if mock.ListFunc == nil {
		panic("PolicySetsAPIMock.ListFunc: method is nil but PolicySetsAPI.List was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.PolicySetListOptions
	}{
		Ctx:          ctx,
		Organization: organization,
		Options:      options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, organization, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedPolicySetsAPI.ListCalls())
func (mock *PolicySetsAPIMock) ListCalls() []struct {
	Ctx          context.Context
	Organization string
	Options      *tfe.PolicySetListOptions
} {
	var calls []struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.PolicySetListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
