// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that PolicyChecksAPIMock does implement PolicyChecksAPI.
// If this is not the case, regenerate this file with moq.
var _ PolicyChecksAPI = &PolicyChecksAPIMock{}

// PolicyChecksAPIMock is a mock implementation of PolicyChecksAPI.
//
//	func TestSomethingThatUsesPolicyChecksAPI(t *testing.T) {
//
//		// make and configure a mocked PolicyChecksAPI
//		mockedPolicyChecksAPI := &PolicyChecksAPIMock{
//			ListFunc: func(ctx context.Context, runID string, options *tfe.PolicyCheckListOptions) (*tfe.PolicyCheckList, error) {
//				panic("mock out the List method")
//			},
//			OverrideFunc: func(ctx context.Context, policyCheckID string) (*tfe.PolicyCheck, error) {
//				panic("mock out the Override method")
//			},
//		}
//
//		// use mockedPolicyChecksAPI in code that requires PolicyChecksAPI
//		// and then make assertions.
//
//	}
type PolicyChecksAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, runID string, options *tfe.PolicyCheckListOptions) (*tfe.PolicyCheckList, error)

	// OverrideFunc mocks the Override method.
	OverrideFunc func(ctx context.Context, policyCheckID string) (*tfe.PolicyCheck, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RunID is the runID argument value.
			RunID string
			// Options is the options argument value.
			Options *tfe.PolicyCheckListOptions
		}
		// Override holds details about calls to the Override method.
		Override []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PolicyCheckID is the policyCheckID argument value.
			PolicyCheckID string
		}
	}
	lockList     sync.RWMutex
	lockOverride sync.RWMutex
}

// List calls ListFunc.
func (mock *PolicyChecksAPIMock) List(ctx context.Context, runID string, options *tfe.PolicyCheckListOptions) (*tfe.PolicyCheckList, error) {
	if mock.ListFunc == nil {
		panic("PolicyChecksAPIMock.ListFunc: method is nil but PolicyChecksAPI.List was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RunID   string
		Options *tfe.PolicyCheckListOptions
	}{
		Ctx:     ctx,
		RunID:   runID,
		Options: options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, runID, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedPolicyChecksAPI.ListCalls())
func (mock *PolicyChecksAPIMock) ListCalls() []struct {
	Ctx     context.Context
	RunID   string
	Options *tfe.PolicyCheckListOptions
} {
	var calls []struct {
		Ctx     context.Context
		RunID   string
		Options *tfe.PolicyCheckListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Override calls OverrideFunc.
func (mock *PolicyChecksAPIMock) Override(ctx context.Context, policyCheckID string) (*tfe.PolicyCheck, error) {
	if mock.OverrideFunc == nil {
		panic("PolicyChecksAPIMock.OverrideFunc: method is nil but PolicyChecksAPI.Override was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		PolicyCheckID string
	}{
		Ctx:           ctx,
		PolicyCheckID: policyCheckID,
	}
	mock.lockOverride.Lock()
	mock.calls.Override = append(mock.calls.Override, callInfo)
	mock.lockOverride.Unlock()
	return mock.OverrideFunc(ctx, policyCheckID)
}

// OverrideCalls gets all the calls that were made to Override.
// Check the length with:
//
//	len(mockedPolicyChecksAPI.OverrideCalls())
func (mock *PolicyChecksAPIMock) OverrideCalls() []struct {
	Ctx           context.Context
	PolicyCheckID string
} {
	var calls []struct {
		Ctx           context.Context
		PolicyCheckID string
	}
	mock.lockOverride.RLock()
	calls = mock.calls.Override
	mock.lockOverride.RUnlock()
	return calls
}
