// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that RegistryModulesAPIMock does implement RegistryModulesAPI.
// If this is not the case, regenerate this file with moq.
var _ RegistryModulesAPI = &RegistryModulesAPIMock{}

// RegistryModulesAPIMock is a mock implementation of RegistryModulesAPI.
//
//	func TestSomethingThatUsesRegistryModulesAPI(t *testing.T) {
//
//		// make and configure a mocked RegistryModulesAPI
//		mockedRegistryModulesAPI := &RegistryModulesAPIMock{
//			ListFunc: func(ctx context.Context, organization string, options *tfe.RegistryModuleListOptions) (*tfe.RegistryModuleList, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedRegistryModulesAPI in code that requires RegistryModulesAPI
//		// and then make assertions.
//
//	}
type RegistryModulesAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, organization string, options *tfe.RegistryModuleListOptions) (*tfe.RegistryModuleList, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization string
			// Options is the options argument value.
			Options *tfe.RegistryModuleListOptions
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *RegistryModulesAPIMock) List(ctx context.Context, organization string, options *tfe.RegistryModuleListOptions) (*tfe.RegistryModuleList, error) {
	if mock.ListFunc == nil {
		panic("RegistryModulesAPIMock.ListFunc: method is nil but RegistryModulesAPI.List was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.RegistryModuleListOptions
	}{
		Ctx:          ctx,
		Organization: organization,
		Options:      options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, organization, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedRegistryModulesAPI.ListCalls())
func (mock *RegistryModulesAPIMock) ListCalls() []struct {
	Ctx          context.Context
	Organization string
	Options      *tfe.RegistryModuleListOptions
} {
	var calls []struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.RegistryModuleListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
