// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that RegistryProvidersAPIMock does implement RegistryProvidersAPI.
// If this is not the case, regenerate this file with moq.
var _ RegistryProvidersAPI = &RegistryProvidersAPIMock{}

// RegistryProvidersAPIMock is a mock implementation of RegistryProvidersAPI.
//
//	func TestSomethingThatUsesRegistryProvidersAPI(t *testing.T) {
//
//		// make and configure a mocked RegistryProvidersAPI
//		mockedRegistryProvidersAPI := &RegistryProvidersAPIMock{
//			ListFunc: func(ctx context.Context, organization string, options *tfe.RegistryProviderListOptions) (*tfe.RegistryProviderList, error) {
//				panic("mock out the List method")
//			},
//			ReadFunc: func(ctx context.Context, providerID tfe.RegistryProviderID, options *tfe.RegistryProviderReadOptions) (*tfe.RegistryProvider, error) {
//				panic("mock out the Read method")
//			},
//		}
//
//		// use mockedRegistryProvidersAPI in code that requires RegistryProvidersAPI
//		// and then make assertions.
//
//	}
type RegistryProvidersAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, organization string, options *tfe.RegistryProviderListOptions) (*tfe.RegistryProviderList, error)

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, providerID tfe.RegistryProviderID, options *tfe.RegistryProviderReadOptions) (*tfe.RegistryProvider, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization string
			// Options is the options argument value.
			Options *tfe.RegistryProviderListOptions
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProviderID is the providerID argument value.
			ProviderID tfe.RegistryProviderID
			// Options is the options argument value.
			Options *tfe.RegistryProviderReadOptions
		}
	}
	lockList sync.RWMutex
	lockRead sync.RWMutex
}

// List calls ListFunc.
func (mock *RegistryProvidersAPIMock) List(ctx context.Context, organization string, options *tfe.RegistryProviderListOptions) (*tfe.RegistryProviderList, error) {
	if mock.ListFunc == nil {
		panic("RegistryProvidersAPIMock.ListFunc: method is nil but RegistryProvidersAPI.List was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.RegistryProviderListOptions
	}{
		Ctx:          ctx,
		Organization: organization,
		Options:      options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, organization, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedRegistryProvidersAPI.ListCalls())
func (mock *RegistryProvidersAPIMock) ListCalls() []struct {
	Ctx          context.Context
	Organization string
	Options      *tfe.RegistryProviderListOptions
} {
	var calls []struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.RegistryProviderListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *RegistryProvidersAPIMock) Read(ctx context.Context, providerID tfe.RegistryProviderID, options *tfe.RegistryProviderReadOptions) (*tfe.RegistryProvider, error) {
	if mock.ReadFunc == nil {
		panic("RegistryProvidersAPIMock.ReadFunc: method is nil but RegistryProvidersAPI.Read was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ProviderID tfe.RegistryProviderID
		Options    *tfe.RegistryProviderReadOptions
	}{
		Ctx:        ctx,
		ProviderID: providerID,
		Options:    options,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, providerID, options)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedRegistryProvidersAPI.ReadCalls())
func (mock *RegistryProvidersAPIMock) ReadCalls() []struct {
	Ctx        context.Context
	ProviderID tfe.RegistryProviderID
	Options    *tfe.RegistryProviderReadOptions
} {
	var calls []struct {
		Ctx        context.Context
		ProviderID tfe.RegistryProviderID
		Options    *tfe.RegistryProviderReadOptions
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Ensure, that RegistryProviderVersionsAPIMock does implement RegistryProviderVersionsAPI.
// If this is not the case, regenerate this file with moq.
var _ RegistryProviderVersionsAPI = &RegistryProviderVersionsAPIMock{}

// RegistryProviderVersionsAPIMock is a mock implementation of RegistryProviderVersionsAPI.
//
//	func TestSomethingThatUsesRegistryProviderVersionsAPI(t *testing.T) {
//
//		// make and configure a mocked RegistryProviderVersionsAPI
//		mockedRegistryProviderVersionsAPI := &RegistryProviderVersionsAPIMock{
//			ListFunc: func(ctx context.Context, providerID tfe.RegistryProviderID, options *tfe.RegistryProviderVersionListOptions) (*tfe.RegistryProviderVersionList, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedRegistryProviderVersionsAPI in code that requires RegistryProviderVersionsAPI
//		// and then make assertions.
//
//	}
type RegistryProviderVersionsAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, providerID tfe.RegistryProviderID, options *tfe.RegistryProviderVersionListOptions) (*tfe.RegistryProviderVersionList, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProviderID is the providerID argument value.
			ProviderID tfe.RegistryProviderID
			// Options is the options argument value.
			Options *tfe.RegistryProviderVersionListOptions
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *RegistryProviderVersionsAPIMock) List(ctx context.Context, providerID tfe.RegistryProviderID, options *tfe.RegistryProviderVersionListOptions) (*tfe.RegistryProviderVersionList, error) {
	if mock.ListFunc == nil {
		panic("RegistryProviderVersionsAPIMock.ListFunc: method is nil but RegistryProviderVersionsAPI.List was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ProviderID tfe.RegistryProviderID
		Options    *tfe.RegistryProviderVersionListOptions
	}{
		Ctx:        ctx,
		ProviderID: providerID,
		Options:    options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, providerID, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedRegistryProviderVersionsAPI.ListCalls())
func (mock *RegistryProviderVersionsAPIMock) ListCalls() []struct {
	Ctx        context.Context
	ProviderID tfe.RegistryProviderID
	Options    *tfe.RegistryProviderVersionListOptions
} {
	var calls []struct {
		Ctx        context.Context
		ProviderID tfe.RegistryProviderID
		Options    *tfe.RegistryProviderVersionListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Ensure, that RegistryProviderPlatformsAPIMock does implement RegistryProviderPlatformsAPI.
// If this is not the case, regenerate this file with moq.
var _ RegistryProviderPlatformsAPI = &RegistryProviderPlatformsAPIMock{}

// RegistryProviderPlatformsAPIMock is a mock implementation of RegistryProviderPlatformsAPI.
//
//	func TestSomethingThatUsesRegistryProviderPlatformsAPI(t *testing.T) {
//
//		// make and configure a mocked RegistryProviderPlatformsAPI
//		mockedRegistryProviderPlatformsAPI := &RegistryProviderPlatformsAPIMock{
//			ListFunc: func(ctx context.Context, versionID tfe.RegistryProviderVersionID, options *tfe.RegistryProviderPlatformListOptions) (*tfe.RegistryProviderPlatformList, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedRegistryProviderPlatformsAPI in code that requires RegistryProviderPlatformsAPI
//		// and then make assertions.
//
//	}
type RegistryProviderPlatformsAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, versionID tfe.RegistryProviderVersionID, options *tfe.RegistryProviderPlatformListOptions) (*tfe.RegistryProviderPlatformList, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VersionID is the versionID argument value.
			VersionID tfe.RegistryProviderVersionID
			// Options is the options argument value.
			Options *tfe.RegistryProviderPlatformListOptions
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *RegistryProviderPlatformsAPIMock) List(ctx context.Context, versionID tfe.RegistryProviderVersionID, options *tfe.RegistryProviderPlatformListOptions) (*tfe.RegistryProviderPlatformList, error) {
	if mock.ListFunc == nil {
		panic("RegistryProviderPlatformsAPIMock.ListFunc: method is nil but RegistryProviderPlatformsAPI.List was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		VersionID tfe.RegistryProviderVersionID
		Options   *tfe.RegistryProviderPlatformListOptions
	}{
		Ctx:       ctx,
		VersionID: versionID,
		Options:   options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, versionID, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedRegistryProviderPlatformsAPI.ListCalls())
func (mock *RegistryProviderPlatformsAPIMock) ListCalls() []struct {
	Ctx       context.Context
	VersionID tfe.RegistryProviderVersionID
	Options   *tfe.RegistryProviderPlatformListOptions
} {
	var calls []struct {
		Ctx       context.Context
		VersionID tfe.RegistryProviderVersionID
		Options   *tfe.RegistryProviderPlatformListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
