// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that RunsAPIMock does implement RunsAPI.
// If this is not the case, regenerate this file with moq.
var _ RunsAPI = &RunsAPIMock{}

// RunsAPIMock is a mock implementation of RunsAPI.
//
//	func TestSomethingThatUsesRunsAPI(t *testing.T) {
//
//		// make and configure a mocked RunsAPI
//		mockedRunsAPI := &RunsAPIMock{
//			ApplyFunc: func(ctx context.Context, runID string, options tfe.RunApplyOptions) error {
//				panic("mock out the Apply method")
//			},
//			CancelFunc: func(ctx context.Context, runID string, options tfe.RunCancelOptions) error {
//				panic("mock out the Cancel method")
//			},
//			CreateFunc: func(ctx context.Context, options tfe.RunCreateOptions) (*tfe.Run, error) {
//				panic("mock out the Create method")
//			},
//			DiscardFunc: func(ctx context.Context, runID string, options tfe.RunDiscardOptions) error {
//				panic("mock out the Discard method")
//			},
//			ForceCancelFunc: func(ctx context.Context, runID string, options tfe.RunForceCancelOptions) error {
//				panic("mock out the ForceCancel method")
//			},
//			ListFunc: func(ctx context.Context, workspaceID string, options *tfe.RunListOptions) (*tfe.RunList, error) {
//				panic("mock out the List method")
//			},
//			ReadFunc: func(ctx context.Context, runID string) (*tfe.Run, error) {
//				panic("mock out the Read method")
//			},
//		}
//
//		// use mockedRunsAPI in code that requires RunsAPI
//		// and then make assertions.
//
//	}
type RunsAPIMock struct {
	// ApplyFunc mocks the Apply method.
	ApplyFunc func(ctx context.Context, runID string, options tfe.RunApplyOptions) error

	// CancelFunc mocks the Cancel method.
	CancelFunc func(ctx context.Context, runID string, options tfe.RunCancelOptions) error

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, options tfe.RunCreateOptions) (*tfe.Run, error)

	// DiscardFunc mocks the Discard method.
	DiscardFunc func(ctx context.Context, runID string, options tfe.RunDiscardOptions) error

	// ForceCancelFunc mocks the ForceCancel method.
	ForceCancelFunc func(ctx context.Context, runID string, options tfe.RunForceCancelOptions) error

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, workspaceID string, options *tfe.RunListOptions) (*tfe.RunList, error)

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, runID string) (*tfe.Run, error)

	// calls tracks calls to the methods.
	calls struct {
		// Apply holds details about calls to the Apply method.
		Apply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RunID is the runID argument value.
			RunID string
			// Options is the options argument value.
			Options tfe.RunApplyOptions
		}
		// Cancel holds details about calls to the Cancel method.
		Cancel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RunID is the runID argument value.
			RunID string
			// Options is the options argument value.
			Options tfe.RunCancelOptions
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options tfe.RunCreateOptions
		}
		// Discard holds details about calls to the Discard method.
		Discard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RunID is the runID argument value.
			RunID string
			// Options is the options argument value.
			Options tfe.RunDiscardOptions
		}
		// ForceCancel holds details about calls to the ForceCancel method.
		ForceCancel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RunID is the runID argument value.
			RunID string
			// Options is the options argument value.
			Options tfe.RunForceCancelOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
			// Options is the options argument value.
			Options *tfe.RunListOptions
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RunID is the runID argument value.
			RunID string
		}
	}
	lockApply       sync.RWMutex
	lockCancel      sync.RWMutex
	lockCreate      sync.RWMutex
	lockDiscard     sync.RWMutex
	lockForceCancel sync.RWMutex
	lockList        sync.RWMutex
	lockRead        sync.RWMutex
}

// Apply calls ApplyFunc.
func (mock *RunsAPIMock) Apply(ctx context.Context, runID string, options tfe.RunApplyOptions) error {
	if mock.ApplyFunc == nil {
		panic("RunsAPIMock.ApplyFunc: method is nil but RunsAPI.Apply was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RunID   string
		Options tfe.RunApplyOptions
	}{
		Ctx:     ctx,
		RunID:   runID,
		Options: options,
	}
	mock.lockApply.Lock()
	mock.calls.Apply = append(mock.calls.Apply, callInfo)
	mock.lockApply.Unlock()
	return mock.ApplyFunc(ctx, runID, options)
}

// ApplyCalls gets all the calls that were made to Apply.
// Check the length with:
//
//	len(mockedRunsAPI.ApplyCalls())
func (mock *RunsAPIMock) ApplyCalls() []struct {
	Ctx     context.Context
	RunID   string
	Options tfe.RunApplyOptions
} {
	var calls []struct {
		Ctx     context.Context
		RunID   string
		Options tfe.RunApplyOptions
	}
	mock.lockApply.RLock()
	calls = mock.calls.Apply
	mock.lockApply.RUnlock()
	return calls
}

// Cancel calls CancelFunc.
func (mock *RunsAPIMock) Cancel(ctx context.Context, runID string, options tfe.RunCancelOptions) error {
	if mock.CancelFunc == nil {
		panic("RunsAPIMock.CancelFunc: method is nil but RunsAPI.Cancel was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RunID   string
		Options tfe.RunCancelOptions
	}{
		Ctx:     ctx,
		RunID:   runID,
		Options: options,
	}
	mock.lockCancel.Lock()
	mock.calls.Cancel = append(mock.calls.Cancel, callInfo)
	mock.lockCancel.Unlock()
	return mock.CancelFunc(ctx, runID, options)
}

// CancelCalls gets all the calls that were made to Cancel.
// Check the length with:
//
//	len(mockedRunsAPI.CancelCalls())
func (mock *RunsAPIMock) CancelCalls() []struct {
	Ctx     context.Context
	RunID   string
	Options tfe.RunCancelOptions
} {
	var calls []struct {
		Ctx     context.Context
		RunID   string
		Options tfe.RunCancelOptions
	}
	mock.lockCancel.RLock()
	calls = mock.calls.Cancel
	mock.lockCancel.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *RunsAPIMock) Create(ctx context.Context, options tfe.RunCreateOptions) (*tfe.Run, error) {
	if mock.CreateFunc == nil {
		panic("RunsAPIMock.CreateFunc: method is nil but RunsAPI.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Options tfe.RunCreateOptions
	}{
		Ctx:     ctx,
		Options: options,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, options)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedRunsAPI.CreateCalls())
func (mock *RunsAPIMock) CreateCalls() []struct {
	Ctx     context.Context
	Options tfe.RunCreateOptions
} {
	var calls []struct {
		Ctx     context.Context
		Options tfe.RunCreateOptions
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Discard calls DiscardFunc.
func (mock *RunsAPIMock) Discard(ctx context.Context, runID string, options tfe.RunDiscardOptions) error {
	if mock.DiscardFunc == nil {
		panic("RunsAPIMock.DiscardFunc: method is nil but RunsAPI.Discard was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RunID   string
		Options tfe.RunDiscardOptions
	}{
		Ctx:     ctx,
		RunID:   runID,
		Options: options,
	}
	mock.lockDiscard.Lock()
	mock.calls.Discard = append(mock.calls.Discard, callInfo)
	mock.lockDiscard.Unlock()
	return mock.DiscardFunc(ctx, runID, options)
}

// DiscardCalls gets all the calls that were made to Discard.
// Check the length with:
//
//	len(mockedRunsAPI.DiscardCalls())
func (mock *RunsAPIMock) DiscardCalls() []struct {
	Ctx     context.Context
	RunID   string
	Options tfe.RunDiscardOptions
} {
	var calls []struct {
		Ctx     context.Context
		RunID   string
		Options tfe.RunDiscardOptions
	}
	mock.lockDiscard.RLock()
	calls = mock.calls.Discard
	mock.lockDiscard.RUnlock()
	return calls
}

// ForceCancel calls ForceCancelFunc.
func (mock *RunsAPIMock) ForceCancel(ctx context.Context, runID string, options tfe.RunForceCancelOptions) error {
	if mock.ForceCancelFunc == nil {
		panic("RunsAPIMock.ForceCancelFunc: method is nil but RunsAPI.ForceCancel was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RunID   string
		Options tfe.RunForceCancelOptions
	}{
		Ctx:     ctx,
		RunID:   runID,
		Options: options,
	}
	mock.lockForceCancel.Lock()
	mock.calls.ForceCancel = append(mock.calls.ForceCancel, callInfo)
	mock.lockForceCancel.Unlock()
	return mock.ForceCancelFunc(ctx, runID, options)
}

// ForceCancelCalls gets all the calls that were made to ForceCancel.
// Check the length with:
//
//	len(mockedRunsAPI.ForceCancelCalls())
func (mock *RunsAPIMock) ForceCancelCalls() []struct {
	Ctx     context.Context
	RunID   string
	Options tfe.RunForceCancelOptions
} {
	var calls []struct {
		Ctx     context.Context
		RunID   string
		Options tfe.RunForceCancelOptions
	}
	mock.lockForceCancel.RLock()
	calls = mock.calls.ForceCancel
	mock.lockForceCancel.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *RunsAPIMock) List(ctx context.Context, workspaceID string, options *tfe.RunListOptions) (*tfe.RunList, error) {
	if mock.ListFunc == nil {
		panic("RunsAPIMock.ListFunc: method is nil but RunsAPI.List was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
		Options     *tfe.RunListOptions
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
		Options:     options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, workspaceID, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedRunsAPI.ListCalls())
func (mock *RunsAPIMock) ListCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
	Options     *tfe.RunListOptions
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
		Options     *tfe.RunListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *RunsAPIMock) Read(ctx context.Context, runID string) (*tfe.Run, error) {
	if mock.ReadFunc == nil {
		panic("RunsAPIMock.ReadFunc: method is nil but RunsAPI.Read was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		RunID string
	}{
		Ctx:   ctx,
		RunID: runID,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, runID)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedRunsAPI.ReadCalls())
func (mock *RunsAPIMock) ReadCalls() []struct {
	Ctx   context.Context
	RunID string
} {
	var calls []struct {
		Ctx   context.Context
		RunID string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}
