// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that OrganizationTagsAPIMock does implement OrganizationTagsAPI.
// If this is not the case, regenerate this file with moq.
var _ OrganizationTagsAPI = &OrganizationTagsAPIMock{}

// OrganizationTagsAPIMock is a mock implementation of OrganizationTagsAPI.
//
//	func TestSomethingThatUsesOrganizationTagsAPI(t *testing.T) {
//
//		// make and configure a mocked OrganizationTagsAPI
//		mockedOrganizationTagsAPI := &OrganizationTagsAPIMock{
//			ListFunc: func(ctx context.Context, organization string, options *tfe.OrganizationTagsListOptions) (*tfe.OrganizationTagsList, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedOrganizationTagsAPI in code that requires OrganizationTagsAPI
//		// and then make assertions.
//
//	}
type OrganizationTagsAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, organization string, options *tfe.OrganizationTagsListOptions) (*tfe.OrganizationTagsList, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization string
			// Options is the options argument value.
			Options *tfe.OrganizationTagsListOptions
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *OrganizationTagsAPIMock) List(ctx context.Context, organization string, options *tfe.OrganizationTagsListOptions) (*tfe.OrganizationTagsList, error) {
	if mock.ListFunc == nil {
		panic("OrganizationTagsAPIMock.ListFunc: method is nil but OrganizationTagsAPI.List was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.OrganizationTagsListOptions
	}{
		Ctx:          ctx,
		Organization: organization,
		Options:      options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, organization, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedOrganizationTagsAPI.ListCalls())
func (mock *OrganizationTagsAPIMock) ListCalls() []struct {
	Ctx          context.Context
	Organization string
	Options      *tfe.OrganizationTagsListOptions
} {
	var calls []struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.OrganizationTagsListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
