// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that TeamsAPIMock does implement TeamsAPI.
// If this is not the case, regenerate this file with moq.
var _ TeamsAPI = &TeamsAPIMock{}

// TeamsAPIMock is a mock implementation of TeamsAPI.
//
//	func TestSomethingThatUsesTeamsAPI(t *testing.T) {
//
//		// make and configure a mocked TeamsAPI
//		mockedTeamsAPI := &TeamsAPIMock{
//			ListFunc: func(ctx context.Context, organization string, options *tfe.TeamListOptions) (*tfe.TeamList, error) {
//				panic("mock out the List method")
//			},
//			ReadFunc: func(ctx context.Context, teamID string) (*tfe.Team, error) {
//				panic("mock out the Read method")
//			},
//		}
//
//		// use mockedTeamsAPI in code that requires TeamsAPI
//		// and then make assertions.
//
//	}
type TeamsAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, organization string, options *tfe.TeamListOptions) (*tfe.TeamList, error)

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, teamID string) (*tfe.Team, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization string
			// Options is the options argument value.
			Options *tfe.TeamListOptions
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TeamID is the teamID argument value.
			TeamID string
		}
	}
	lockList sync.RWMutex
	lockRead sync.RWMutex
}

// List calls ListFunc.
func (mock *TeamsAPIMock) List(ctx context.Context, organization string, options *tfe.TeamListOptions) (*tfe.TeamList, error) {
	if mock.ListFunc == nil {
		panic("TeamsAPIMock.ListFunc: method is nil but TeamsAPI.List was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.TeamListOptions
	}{
		Ctx:          ctx,
		Organization: organization,
		Options:      options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, organization, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedTeamsAPI.ListCalls())
func (mock *TeamsAPIMock) ListCalls() []struct {
	Ctx          context.Context
	Organization string
	Options      *tfe.TeamListOptions
} {
	var calls []struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.TeamListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *TeamsAPIMock) Read(ctx context.Context, teamID string) (*tfe.Team, error) {
	if mock.ReadFunc == nil {
		panic("TeamsAPIMock.ReadFunc: method is nil but TeamsAPI.Read was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		TeamID string
	}{
		Ctx:    ctx,
		TeamID: teamID,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, teamID)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedTeamsAPI.ReadCalls())
func (mock *TeamsAPIMock) ReadCalls() []struct {
	Ctx    context.Context
	TeamID string
} {
	var calls []struct {
		Ctx    context.Context
		TeamID string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Ensure, that OrganizationMembershipsAPIMock does implement OrganizationMembershipsAPI.
// If this is not the case, regenerate this file with moq.
var _ OrganizationMembershipsAPI = &OrganizationMembershipsAPIMock{}

// OrganizationMembershipsAPIMock is a mock implementation of OrganizationMembershipsAPI.
//
//	func TestSomethingThatUsesOrganizationMembershipsAPI(t *testing.T) {
//
//		// make and configure a mocked OrganizationMembershipsAPI
//		mockedOrganizationMembershipsAPI := &OrganizationMembershipsAPIMock{
//			ReadFunc: func(ctx context.Context, orgMemID string) (*tfe.OrganizationMembership, error) {
//				panic("mock out the Read method")
//			},
//		}
//
//		// use mockedOrganizationMembershipsAPI in code that requires OrganizationMembershipsAPI
//		// and then make assertions.
//
//	}
type OrganizationMembershipsAPIMock struct {
	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, orgMemID string) (*tfe.OrganizationMembership, error)

	// calls tracks calls to the methods.
	calls struct {
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgMemID is the orgMemID argument value.
			OrgMemID string
		}
	}
	lockRead sync.RWMutex
}

// Read calls ReadFunc.
func (mock *OrganizationMembershipsAPIMock) Read(ctx context.Context, orgMemID string) (*tfe.OrganizationMembership, error) {
	if mock.ReadFunc == nil {
		panic("OrganizationMembershipsAPIMock.ReadFunc: method is nil but OrganizationMembershipsAPI.Read was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		OrgMemID string
	}{
		Ctx:      ctx,
		OrgMemID: orgMemID,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, orgMemID)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedOrganizationMembershipsAPI.ReadCalls())
func (mock *OrganizationMembershipsAPIMock) ReadCalls() []struct {
	Ctx      context.Context
	OrgMemID string
} {
	var calls []struct {
		Ctx      context.Context
		OrgMemID string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}
