// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that TeamAccessAPIMock does implement TeamAccessAPI.
// If this is not the case, regenerate this file with moq.
var _ TeamAccessAPI = &TeamAccessAPIMock{}

// TeamAccessAPIMock is a mock implementation of TeamAccessAPI.
//
//	func TestSomethingThatUsesTeamAccessAPI(t *testing.T) {
//
//		// make and configure a mocked TeamAccessAPI
//		mockedTeamAccessAPI := &TeamAccessAPIMock{
//			ListFunc: func(ctx context.Context, options *tfe.TeamAccessListOptions) (*tfe.TeamAccessList, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedTeamAccessAPI in code that requires TeamAccessAPI
//		// and then make assertions.
//
//	}
type TeamAccessAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, options *tfe.TeamAccessListOptions) (*tfe.TeamAccessList, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Options is the options argument value.
			Options *tfe.TeamAccessListOptions
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *TeamAccessAPIMock) List(ctx context.Context, options *tfe.TeamAccessListOptions) (*tfe.TeamAccessList, error) {
	if mock.ListFunc == nil {
		panic("TeamAccessAPIMock.ListFunc: method is nil but TeamAccessAPI.List was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Options *tfe.TeamAccessListOptions
	}{
		Ctx:     ctx,
		Options: options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedTeamAccessAPI.ListCalls())
func (mock *TeamAccessAPIMock) ListCalls() []struct {
	Ctx     context.Context
	Options *tfe.TeamAccessListOptions
} {
	var calls []struct {
		Ctx     context.Context
		Options *tfe.TeamAccessListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
