// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that VariablesAPIMock does implement VariablesAPI.
// If this is not the case, regenerate this file with moq.
var _ VariablesAPI = &VariablesAPIMock{}

// VariablesAPIMock is a mock implementation of VariablesAPI.
//
//	func TestSomethingThatUsesVariablesAPI(t *testing.T) {
//
//		// make and configure a mocked VariablesAPI
//		mockedVariablesAPI := &VariablesAPIMock{
//			CreateFunc: func(ctx context.Context, workspaceID string, options tfe.VariableCreateOptions) (*tfe.Variable, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, workspaceID string, variableID string) error {
//				panic("mock out the Delete method")
//			},
//			ListFunc: func(ctx context.Context, workspaceID string, options *tfe.VariableListOptions) (*tfe.VariableList, error) {
//				panic("mock out the List method")
//			},
//			ReadFunc: func(ctx context.Context, workspaceID string, variableID string) (*tfe.Variable, error) {
//				panic("mock out the Read method")
//			},
//			UpdateFunc: func(ctx context.Context, workspaceID string, variableID string, options tfe.VariableUpdateOptions) (*tfe.Variable, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedVariablesAPI in code that requires VariablesAPI
//		// and then make assertions.
//
//	}
type VariablesAPIMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, workspaceID string, options tfe.VariableCreateOptions) (*tfe.Variable, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, workspaceID string, variableID string) error

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, workspaceID string, options *tfe.VariableListOptions) (*tfe.VariableList, error)

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, workspaceID string, variableID string) (*tfe.Variable, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, workspaceID string, variableID string, options tfe.VariableUpdateOptions) (*tfe.Variable, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
			// Options is the options argument value.
			Options tfe.VariableCreateOptions
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
			// VariableID is the variableID argument value.
			VariableID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
			// Options is the options argument value.
			Options *tfe.VariableListOptions
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
			// VariableID is the variableID argument value.
			VariableID string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
			// VariableID is the variableID argument value.
			VariableID string
			// Options is the options argument value.
			Options tfe.VariableUpdateOptions
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockList   sync.RWMutex
	lockRead   sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *VariablesAPIMock) Create(ctx context.Context, workspaceID string, options tfe.VariableCreateOptions) (*tfe.Variable, error) {
	if mock.CreateFunc == nil {
		panic("VariablesAPIMock.CreateFunc: method is nil but VariablesAPI.Create was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
		Options     tfe.VariableCreateOptions
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
		Options:     options,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, workspaceID, options)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedVariablesAPI.CreateCalls())
func (mock *VariablesAPIMock) CreateCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
	Options     tfe.VariableCreateOptions
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
		Options     tfe.VariableCreateOptions
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *VariablesAPIMock) Delete(ctx context.Context, workspaceID string, variableID string) error {
	if mock.DeleteFunc == nil {
		panic("VariablesAPIMock.DeleteFunc: method is nil but VariablesAPI.Delete was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
		VariableID  string
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
		VariableID:  variableID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, workspaceID, variableID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedVariablesAPI.DeleteCalls())
func (mock *VariablesAPIMock) DeleteCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
	VariableID  string
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
		VariableID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *VariablesAPIMock) List(ctx context.Context, workspaceID string, options *tfe.VariableListOptions) (*tfe.VariableList, error) {
	if mock.ListFunc == nil {
		panic("VariablesAPIMock.ListFunc: method is nil but VariablesAPI.List was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
		Options     *tfe.VariableListOptions
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
		Options:     options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, workspaceID, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedVariablesAPI.ListCalls())
func (mock *VariablesAPIMock) ListCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
	Options     *tfe.VariableListOptions
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
		Options     *tfe.VariableListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *VariablesAPIMock) Read(ctx context.Context, workspaceID string, variableID string) (*tfe.Variable, error) {
	if mock.ReadFunc == nil {
		panic("VariablesAPIMock.ReadFunc: method is nil but VariablesAPI.Read was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
		VariableID  string
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
		VariableID:  variableID,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, workspaceID, variableID)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedVariablesAPI.ReadCalls())
func (mock *VariablesAPIMock) ReadCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
	VariableID  string
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
		VariableID  string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *VariablesAPIMock) Update(ctx context.Context, workspaceID string, variableID string, options tfe.VariableUpdateOptions) (*tfe.Variable, error) {
	if mock.UpdateFunc == nil {
		panic("VariablesAPIMock.UpdateFunc: method is nil but VariablesAPI.Update was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
		VariableID  string
		Options     tfe.VariableUpdateOptions
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
		VariableID:  variableID,
		Options:     options,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, workspaceID, variableID, options)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedVariablesAPI.UpdateCalls())
func (mock *VariablesAPIMock) UpdateCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
	VariableID  string
	Options     tfe.VariableUpdateOptions
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
		VariableID  string
		Options     tfe.VariableUpdateOptions
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
