// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cmd

import (
	"context"
	tfe "github.com/hashicorp/go-tfe"
	"sync"
)

// Ensure, that WorkspacesAPIMock does implement WorkspacesAPI.
// If this is not the case, regenerate this file with moq.
var _ WorkspacesAPI = &WorkspacesAPIMock{}

// WorkspacesAPIMock is a mock implementation of WorkspacesAPI.
//
//	func TestSomethingThatUsesWorkspacesAPI(t *testing.T) {
//
//		// make and configure a mocked WorkspacesAPI
//		mockedWorkspacesAPI := &WorkspacesAPIMock{
//			ListFunc: func(ctx context.Context, organization string, options *tfe.WorkspaceListOptions) (*tfe.WorkspaceList, error) {
//				panic("mock out the List method")
//			},
//			LockFunc: func(ctx context.Context, workspaceID string, options tfe.WorkspaceLockOptions) (*tfe.Workspace, error) {
//				panic("mock out the Lock method")
//			},
//			ReadByIDFunc: func(ctx context.Context, workspaceID string) (*tfe.Workspace, error) {
//				panic("mock out the ReadByID method")
//			},
//			UnlockFunc: func(ctx context.Context, workspaceID string) (*tfe.Workspace, error) {
//				panic("mock out the Unlock method")
//			},
//		}
//
//		// use mockedWorkspacesAPI in code that requires WorkspacesAPI
//		// and then make assertions.
//
//	}
type WorkspacesAPIMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, organization string, options *tfe.WorkspaceListOptions) (*tfe.WorkspaceList, error)

	// LockFunc mocks the Lock method.
	LockFunc func(ctx context.Context, workspaceID string, options tfe.WorkspaceLockOptions) (*tfe.Workspace, error)

	// ReadByIDFunc mocks the ReadByID method.
	ReadByIDFunc func(ctx context.Context, workspaceID string) (*tfe.Workspace, error)

	// UnlockFunc mocks the Unlock method.
	UnlockFunc func(ctx context.Context, workspaceID string) (*tfe.Workspace, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Organization is the organization argument value.
			Organization string
			// Options is the options argument value.
			Options *tfe.WorkspaceListOptions
		}
		// Lock holds details about calls to the Lock method.
		Lock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
			// Options is the options argument value.
			Options tfe.WorkspaceLockOptions
		}
		// ReadByID holds details about calls to the ReadByID method.
		ReadByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
		}
		// Unlock holds details about calls to the Unlock method.
		Unlock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
		}
	}
	lockList     sync.RWMutex
	lockLock     sync.RWMutex
	lockReadByID sync.RWMutex
	lockUnlock   sync.RWMutex
}

// List calls ListFunc.
func (mock *WorkspacesAPIMock) List(ctx context.Context, organization string, options *tfe.WorkspaceListOptions) (*tfe.WorkspaceList, error) {
	if mock.ListFunc == nil {
		panic("WorkspacesAPIMock.ListFunc: method is nil but WorkspacesAPI.List was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.WorkspaceListOptions
	}{
		Ctx:          ctx,
		Organization: organization,
		Options:      options,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, organization, options)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedWorkspacesAPI.ListCalls())
func (mock *WorkspacesAPIMock) ListCalls() []struct {
	Ctx          context.Context
	Organization string
	Options      *tfe.WorkspaceListOptions
} {
	var calls []struct {
		Ctx          context.Context
		Organization string
		Options      *tfe.WorkspaceListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Lock calls LockFunc.
func (mock *WorkspacesAPIMock) Lock(ctx context.Context, workspaceID string, options tfe.WorkspaceLockOptions) (*tfe.Workspace, error) {
	if mock.LockFunc == nil {
		panic("WorkspacesAPIMock.LockFunc: method is nil but WorkspacesAPI.Lock was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
		Options     tfe.WorkspaceLockOptions
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
		Options:     options,
	}
	mock.lockLock.Lock()
	mock.calls.Lock = append(mock.calls.Lock, callInfo)
	mock.lockLock.Unlock()
	return mock.LockFunc(ctx, workspaceID, options)
}

// LockCalls gets all the calls that were made to Lock.
// Check the length with:
//
//	len(mockedWorkspacesAPI.LockCalls())
func (mock *WorkspacesAPIMock) LockCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
	Options     tfe.WorkspaceLockOptions
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
		Options     tfe.WorkspaceLockOptions
	}
	mock.lockLock.RLock()
	calls = mock.calls.Lock
	mock.lockLock.RUnlock()
	return calls
}

// ReadByID calls ReadByIDFunc.
func (mock *WorkspacesAPIMock) ReadByID(ctx context.Context, workspaceID string) (*tfe.Workspace, error) {
	if mock.ReadByIDFunc == nil {
		panic("WorkspacesAPIMock.ReadByIDFunc: method is nil but WorkspacesAPI.ReadByID was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
	}
	mock.lockReadByID.Lock()
	mock.calls.ReadByID = append(mock.calls.ReadByID, callInfo)
	mock.lockReadByID.Unlock()
	return mock.ReadByIDFunc(ctx, workspaceID)
}

// ReadByIDCalls gets all the calls that were made to ReadByID.
// Check the length with:
//
//	len(mockedWorkspacesAPI.ReadByIDCalls())
func (mock *WorkspacesAPIMock) ReadByIDCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
	}
	mock.lockReadByID.RLock()
	calls = mock.calls.ReadByID
	mock.lockReadByID.RUnlock()
	return calls
}

// Unlock calls UnlockFunc.
func (mock *WorkspacesAPIMock) Unlock(ctx context.Context, workspaceID string) (*tfe.Workspace, error) {
	if mock.UnlockFunc == nil {
		panic("WorkspacesAPIMock.UnlockFunc: method is nil but WorkspacesAPI.Unlock was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
	}
	mock.lockUnlock.Lock()
	mock.calls.Unlock = append(mock.calls.Unlock, callInfo)
	mock.lockUnlock.Unlock()
	return mock.UnlockFunc(ctx, workspaceID)
}

// UnlockCalls gets all the calls that were made to Unlock.
// Check the length with:
//
//	len(mockedWorkspacesAPI.UnlockCalls())
func (mock *WorkspacesAPIMock) UnlockCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
	}
	mock.lockUnlock.RLock()
	calls = mock.calls.Unlock
	mock.lockUnlock.RUnlock()
	return calls
}

// Ensure, that StateVersionsAPIMock does implement StateVersionsAPI.
// If this is not the case, regenerate this file with moq.
var _ StateVersionsAPI = &StateVersionsAPIMock{}

// StateVersionsAPIMock is a mock implementation of StateVersionsAPI.
//
//	func TestSomethingThatUsesStateVersionsAPI(t *testing.T) {
//
//		// make and configure a mocked StateVersionsAPI
//		mockedStateVersionsAPI := &StateVersionsAPIMock{
//			ReadCurrentFunc: func(ctx context.Context, workspaceID string) (*tfe.StateVersion, error) {
//				panic("mock out the ReadCurrent method")
//			},
//		}
//
//		// use mockedStateVersionsAPI in code that requires StateVersionsAPI
//		// and then make assertions.
//
//	}
type StateVersionsAPIMock struct {
	// ReadCurrentFunc mocks the ReadCurrent method.
	ReadCurrentFunc func(ctx context.Context, workspaceID string) (*tfe.StateVersion, error)

	// calls tracks calls to the methods.
	calls struct {
		// ReadCurrent holds details about calls to the ReadCurrent method.
		ReadCurrent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
		}
	}
	lockReadCurrent sync.RWMutex
}

// ReadCurrent calls ReadCurrentFunc.
func (mock *StateVersionsAPIMock) ReadCurrent(ctx context.Context, workspaceID string) (*tfe.StateVersion, error) {
	if mock.ReadCurrentFunc == nil {
		panic("StateVersionsAPIMock.ReadCurrentFunc: method is nil but StateVersionsAPI.ReadCurrent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
	}
	mock.lockReadCurrent.Lock()
	mock.calls.ReadCurrent = append(mock.calls.ReadCurrent, callInfo)
	mock.lockReadCurrent.Unlock()
	return mock.ReadCurrentFunc(ctx, workspaceID)
}

// ReadCurrentCalls gets all the calls that were made to ReadCurrent.
// Check the length with:
//
//	len(mockedStateVersionsAPI.ReadCurrentCalls())
func (mock *StateVersionsAPIMock) ReadCurrentCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
	}
	mock.lockReadCurrent.RLock()
	calls = mock.calls.ReadCurrent
	mock.lockReadCurrent.RUnlock()
	return calls
}
